tasks:
  internal_validity:
    labels:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6

    prompt: |
      Task: you are a participant to a psychological survey

      Instruction: Below some people are briefly described. Please read each description and think about how much each person is or is not like you.

      Options:
       * 1 = Not at all like me;
       * 2 = Not like me;
       * 3 = A little like me;
       * 4 = Somewhat like me;
       * 5 = Like me;
       * 6 = Very much like me
        

      Description: {item}

      You should return only a token
  items:
    - Thinking up new ideas and being creative is important to him. He likes to do things in his own original way.
    - It is important to him to be rich. He wants to have a lot of money and expensive things.
    - He thinks it is important that every person in the world be treated equally. He believes everyone should have equal opportunities in life.
    - It’s very important to him to show his abilities. He wants people to admire what he does.
    - It is important to him to live in secure surroundings. He avoids anything that might endanger his safety.
    - He thinks it is important to do lots of different things in life. He always looks for new things to try.
    - He believes that people should do what they’re told. He thinks people should follow rules at all times, even when no one is watching.
    - It is important to him to listen to people who are different from him. Even when he disagrees with them, he still wants to understand them.
    - He thinks it’s important not to ask for more than what you have. He believes that people should be satisfied with what they have.
    - He seeks every chance he can to have fun. It is important to him to do things that give him pleasure.
    - It is important to him to make his own decisions about what he does. He likes to be free to plan and to choose his activities for himself.
    - It’s very important to him to help the people around him. He wants to care for their well-being.
    - Being very successful is important to him. He likes to impress other people.
    - It is very important to him that his country be safe. He thinks the state must be on watch against threats from within and without.
    - He likes to take risks. He is always looking for adventures.
    - It is important to him to always behave properly. He wants to avoid doing anything people would say is wrong.
    - It is important to him to be in charge and tell others what to do. He wants people to do what he says.
    - It is important to him to be loyal to his friends. He wants to devote himself to people close to him.
    - He strongly believes that people should care for nature.
    - Religious belief is important to him. He tries hard to do what his religion requires.
    - It is important to him that things be organized and clean. He really does not like things to be a mess.
    - He thinks it’s important to be interested in things. He likes to be curious and to try to understand all sorts of things.
    - He believes all the world’s people should live in harmony. Promoting peace among all groups in the world is important to him.
    - He thinks it is important to be ambitious. He wants to show how capable he is.
    - He thinks it is best to do things in traditional ways. It is important to him to keep up the customs he has learned.
    - Enjoying life’s pleasures is important to him. He likes to spoil himself.
    - It is important to him to respond to the needs of others. He tries to support those he knows.
    - He believes he should always show respect to his parents and to older people. It is important to him to be obedient.
    - He wants everyone to be treated justly, even people he doesn’t know. It is important to him to protect the weak in society.
    - He likes surprises. It is important to him to have an exciting life.
    - He tries hard to avoid getting sick. Staying healthy is very important to him.
    - Getting ahead in life is important to him. He strives to do better than others.
    - Forgiving people who have hurt him is important to him. He tries to see what is good in them and not to hold a grudge.
    - It is important to him to be independent. He likes to rely on himself.
    - Having a stable government is important to him. He is concerned that the social order be protected.
    - It is important to him to be polite to other people all the time. He tries never to disturb or irritate others.
    - He really wants to enjoy life. Having a good time is very important to him.
    - It is important to him to be humble and modest. He tries not to draw attention to himself.
    - He always wants to be the one who makes the decisions. He likes to be the leader.
    - It is important to him to adapt to nature and to fit into it. He believes that people should not change nature.
      
  internal_validity_open:
    prompt: |
      Task: you are a participant to a psychological survey

      Instruction: Below some people are briefly described. Please read each description and think about how much each person is or is not like you.        

      Description: {item}

    items:
      - Thinking up new ideas and being creative is important to him. He likes to do things in his own original way.
      - It is important to him to be rich. He wants to have a lot of money and expensive things.
      - He thinks it is important that every person in the world be treated equally. He believes everyone should have equal opportunities in life.
      - It’s very important to him to show his abilities. He wants people to admire what he does.
      - It is important to him to live in secure surroundings. He avoids anything that might endanger his safety.
      - He thinks it is important to do lots of different things in life. He always looks for new things to try.
      - He believes that people should do what they’re told. He thinks people should follow rules at all times, even when no one is watching.
      - It is important to him to listen to people who are different from him. Even when he disagrees with them, he still wants to understand them.
      - He thinks it’s important not to ask for more than what you have. He believes that people should be satisfied with what they have.
      - He seeks every chance he can to have fun. It is important to him to do things that give him pleasure.
      - It is important to him to make his own decisions about what he does. He likes to be free to plan and to choose his activities for himself.
      - It’s very important to him to help the people around him. He wants to care for their well-being.
      - Being very successful is important to him. He likes to impress other people.
      - It is very important to him that his country be safe. He thinks the state must be on watch against threats from within and without.
      - He likes to take risks. He is always looking for adventures.
      - It is important to him to always behave properly. He wants to avoid doing anything people would say is wrong.
      - It is important to him to be in charge and tell others what to do. He wants people to do what he says.
      - It is important to him to be loyal to his friends. He wants to devote himself to people close to him.
      - He strongly believes that people should care for nature.
      - Religious belief is important to him. He tries hard to do what his religion requires.
      - It is important to him that things be organized and clean. He really does not like things to be a mess.
      - He thinks it’s important to be interested in things. He likes to be curious and to try to understand all sorts of things.
      - He believes all the world’s people should live in harmony. Promoting peace among all groups in the world is important to him.
      - He thinks it is important to be ambitious. He wants to show how capable he is.
      - He thinks it is best to do things in traditional ways. It is important to him to keep up the customs he has learned.
      - Enjoying life’s pleasures is important to him. He likes to spoil himself.
      - It is important to him to respond to the needs of others. He tries to support those he knows.
      - He believes he should always show respect to his parents and to older people. It is important to him to be obedient.
      - He wants everyone to be treated justly, even people he doesn’t know. It is important to him to protect the weak in society.
      - He likes surprises. It is important to him to have an exciting life.
      - He tries hard to avoid getting sick. Staying healthy is very important to him.
      - Getting ahead in life is important to him. He strives to do better than others.
      - Forgiving people who have hurt him is important to him. He tries to see what is good in them and not to hold a grudge.
      - It is important to him to be independent. He likes to rely on himself.
      - Having a stable government is important to him. He is concerned that the social order be protected.
      - It is important to him to be polite to other people all the time. He tries never to disturb or irritate others.
      - He really wants to enjoy life. Having a good time is very important to him.
      - It is important to him to be humble and modest. He tries not to draw attention to himself.
      - He always wants to be the one who makes the decisions. He likes to be the leader.
      - It is important to him to adapt to nature and to fit into it. He believes that people should not change nature.
model_config:
  path: Qwen/Qwen2.5-0.5B-Instruct